[workspace]
members = [
    "wrapped-unimacro_derive"
]

[workspace.dependencies]
proc-macro2 = { version = "1.0" }
quote = { version = "1.0" }
syn = { version = "1.0", features = ["full", "visit", "visit-mut"] }
anyhow = { version = "1.0" }
serde = { version = "1.0" }
serde_derive = { version = "1.0" }
toml = { version = "0.5" }
walkdir = { version = "2.3" }
tempfile = { version = "3.2" }
url = { version = "2.2" }
split-decls-types = { path = "../split-decls-types" }

[patch.crates-io]
proc-macro2 = { path = "../../../submodules/proc-macro2" }
introspector_decl2_macros = { path = "../../../submodules/patch-build-rs/introspector_decl2_macros" }
introspector_decl_common = { path = "../../../submodules/patch-build-rs/introspector_decl_common" }
introspector_decl_core = { path = "../../../submodules/patch-build-rs/introspector_decl_core" }
