// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:71 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs at 2025-12-23T17:36:48.268781019+00:00
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
fn should_skip_dir(path: &Path) -> bool {
    let name = path.file_name().unwrap().to_string_lossy();
    matches!(name.as_ref(), "target" | ".git" | "node_modules")
}
