// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:71 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs at 2025-12-23T17:36:49.188112769+00:00
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
pub fn path_relative_from(path: &Path, base: &Path) -> Option<PathBuf> {
    let mut relativized_path = PathBuf::new();
    let mut common_prefix = 0;
    for (p_comp, b_comp) in path.components().zip(base.components()) {
        if p_comp == b_comp {
            common_prefix += 1;
        } else {
            break;
        }
    }
    let num_up = base.components().count() - common_prefix;
    for _ in 0..num_up {
        relativized_path.push("..");
    }
    for p_comp in path.components().skip(common_prefix) {
        relativized_path.push(p_comp);
    }
    if relativized_path.as_os_str().is_empty() {
        Some(PathBuf::from("."))
    } else {
        Some(relativized_path)
    }
}
