// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:71 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs at 2025-12-23T17:27:47.126556991+00:00
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
fn find_all_cargo_tomls(dir: &Path, verbose: bool) -> Result<Vec<PathBuf>> {
    let mut cargo_tomls = Vec::new();
    if dir.is_dir() {
        if verbose {
            println!("  Scanning directory: {}", dir.display());
        }
        for entry in fs::read_dir(dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.is_file() && path.file_name() == Some("Cargo.toml".as_ref()) {
                if verbose {
                    println!("    Found Cargo.toml: {}", path.display());
                }
                cargo_tomls.push(path);
            }
        }
    }
    Ok(cargo_tomls)
}
