// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:71 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs at 2025-12-23T17:36:48.204241981+00:00
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
pub fn copy_dir_recursive(src: &Path, dst: &Path) -> Result<()> {
    fs::create_dir_all(dst).context(format!(
        "Failed to create destination directory {}",
        dst.display()
    ))?;
    for entry in
        fs::read_dir(src).context(format!("Failed to read source directory {}", src.display()))?
    {
        let entry = entry?;
        let ty = entry.file_type()?;
        if ty.is_dir() {
            copy_dir_recursive(&entry.path(), &dst.join(entry.file_name()))?;
        } else {
            fs::copy(&entry.path(), &dst.join(entry.file_name())).context(format!(
                "Failed to copy file from {} to {}",
                entry.path().display(),
                dst.join(entry.file_name()).display()
            ))?;
        }
    }
    Ok(())
}
