use anyhow::{Context, Result};
use proc_macro2::{Ident, Span, TokenStream};
use quote::ToTokens;
use std::fs;
use syn::visit::Visit;
use syn::{self};

use crate::CratePaths;
use split_decls_types::SplitDeclsConfig;

// Import new modules
pub mod use_collector;
pub mod declaration_extractor;
pub mod declaration_writer;
pub mod invocation_generator;

/// Main entry point for eager splitting of a crate
pub fn eager_split_crate(paths: &CratePaths, config: &SplitDeclsConfig) -> Result<()> {
    // 1. Backup original files
    backup_original_files(paths)?;
    
    // 2. Parse the original lib.rs
    let lib_content = fs::read_to_string(&paths.old_lib_rs_path)
        .context(format!("Failed to read {}", paths.old_lib_rs_path.display()))?;
    
    let syntax_tree: syn::File = syn::parse_file(&lib_content)
        .context("Failed to parse lib.rs as Rust code")?;
    
    // 3. Split declarations into individual files
    split_and_generate_decls(&syntax_tree, paths, config, false)?;
    
    // 4. Generate new lib.rs
    generate_new_lib_rs(paths)?;
    
    // 5. Generate new build.rs
    generate_new_build_rs(paths)?;
    
    println!("Eager splitting completed for crate: {}", paths.crate_name);
    Ok(())
}

/// Backup original files before modification
fn backup_original_files(paths: &CratePaths) -> Result<()> {
    // Backup lib.rs to oldlib.rs
    if paths.lib_rs_path.exists() {
        fs::copy(&paths.lib_rs_path, &paths.old_lib_rs_path)
            .context(format!("Failed to backup {} to {}", 
                paths.lib_rs_path.display(), paths.old_lib_rs_path.display()))?;
        println!("Backed up lib.rs to oldlib.rs");
    }
    
    // Backup build.rs to oldbuild.rs if it exists
    if paths.build_rs_path.exists() {
        fs::copy(&paths.build_rs_path, &paths.old_build_rs_path)
            .context(format!("Failed to backup {} to {}", 
                paths.build_rs_path.display(), paths.old_build_rs_path.display()))?;
        println!("Backed up build.rs to oldbuild.rs");
    }
    
    Ok(())
}

/// Generate new lib.rs that re-exports the split declarations
fn generate_new_lib_rs(paths: &CratePaths) -> Result<()> {
    let new_lib_content = format!(r#"// Generated by split-decls-rs
// Re-exports all split declarations

pub mod decls {{
    include!("decls/_decl_module_invocation.rs");
}}
pub use decls::*;

// Re-export prelude macros if available
#[cfg(feature = "introspector_decl2_macros")]
pub use introspector_decl2_macros::*;
"#);
    
    fs::write(&paths.lib_rs_path, new_lib_content)
        .context(format!("Failed to write new lib.rs at {}", paths.lib_rs_path.display()))?;
    
    println!("Generated new lib.rs");
    Ok(())
}

/// Generate new build.rs for monitoring changes
fn generate_new_build_rs(paths: &CratePaths) -> Result<()> {
    let build_content = format!(r#"// Generated by split-decls-rs
use anyhow::Result;

fn main() -> Result<()> {{
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/oldlib.rs");
    println!("cargo:rerun-if-changed=.split-decls-config.toml");
    
    // This build.rs monitors for changes that would require re-running split-decls-rs
    println!("cargo:note=build.rs finished. If split-decls-rs needs to be re-run, changes will be detected.");
    
    Ok(())
}}
"#);
    
    fs::write(&paths.build_rs_path, build_content)
        .context(format!("Failed to write new build.rs at {}", paths.build_rs_path.display()))?;
    
    println!("Generated new build.rs");
    Ok(())
}

/// Performs the eager splitting of the AST into individual declaration files and generates
/// the `_decl_module_invocation.rs` file.
pub fn split_and_generate_decls(
    syntax_tree: &syn::File,
    paths: &CratePaths,
    config: &SplitDeclsConfig,
    dry_run: bool,
) -> Result<()> {
    // Ensure the output directory exists
    if !dry_run {
        fs::create_dir_all(&paths.decls_output_dir)
            .context(format!("Failed to create directory {}", paths.decls_output_dir.display()))?;
        println!("Created directory: {}", paths.decls_output_dir.display());
    } else {
        println!(
            "Dry-run: Would create directory: {}",
            paths.decls_output_dir.display()
        );
    }

    // Collect use statements
    let mut use_collector_instance = use_collector::UseStatementCollector::default();
    use_collector_instance.visit_file(syntax_tree);
    let common_uses: TokenStream = use_collector_instance.uses.iter().map(|u| u.to_token_stream()).collect();

    let mut collected_module_names: Vec<Ident> = Vec::new();
    let mut item_count = 0; // For generating unique names for impls without explicit paths

    // Extract and split declarations
    for item in &syntax_tree.items {
        if let Some(decl) = declaration_extractor::extract_single_declaration(item, item_count) {
            let module_name_str = format!("{}_decls_{}", paths.crate_name.replace("-", "_"), decl.name);
            let module_name_ident = Ident::new(&module_name_str, Span::call_site());
            collected_module_names.push(module_name_ident.clone());

            declaration_writer::write_declaration_file(
                decl,
                paths,
                config,
                dry_run,
                &common_uses,
                module_name_ident,
            )?;
        }
        item_count += 1;
    }

    // Generate decl_module! invocation
    invocation_generator::generate_decl_module_invocation(collected_module_names, paths, dry_run)?;

    Ok(())
}