use std::fs;
use anyhow::{Context, Result};
use quote::quote;
use crate::CratePaths;

/// Generates the new, minimal src/lib.rs for the crate.
pub fn generate_new_lib_rs(paths: &CratePaths, dry_run: bool) -> Result<()> {
    // 2. Generate new src/lib.rs for the crate
    // This new lib.rs will simply re-export items from the 'decls' module
    // and potentially other macros. The actual declarations will be in src/decls/*.rs
    let new_lib_rs_content = quote! {
        // Re-export prelude macros if desired
        pub use introspector_decl2_macros::prelude::*;

        // Include the module generated by the split-decls-rs tool (eagerly)
        pub mod decls;
        pub use decls::*;
    };

    if dry_run {
        let new_path = paths.lib_rs_path.with_extension("new");
        fs::write(&new_path, new_lib_rs_content.to_string())
            .context(format!("Failed to write new lib.rs to {}", new_path.display()))?;
        println!("Dry-run: Generated new src/lib.rs content to {} for crate {}", new_path.display(), paths.crate_name);
    } else {
        fs::write(&paths.lib_rs_path, new_lib_rs_content.to_string())
            .context(format!("Failed to write new lib.rs to {}", paths.lib_rs_path.display()))?;
        println!("Generated new src/lib.rs for crate {}", paths.crate_name);
    }
    Ok(())
}
