pub fn specialprint(macro_name: &str, local_score: f64) {
    print!(", {}: {:.4}", macro_name, local_score);
}

#[macro_export]
macro_rules! add_generated_header {
    ($path:expr, $content:expr) => {{
        use chrono::Utc;
        use std::io::Write; // Ensure Write trait is in scope for fs::write

        let source_info = format!(
            "# Generated by {} at {}\n# Do not edit this file by hand. Your changes will be overwritten.\n\n",
            file!(),
            Utc::now().to_rfc3339()
        );
        let final_content = source_info + $content;
        std::fs::write($path, final_content)
    }};
}
