// build_helpers/cargo_toml_parts/mod.rs

macro_rules! define_package_config {
    () => {
        package {
            name = "split-decls-rs", // This is the actual name of the crate where build.rs resides
            version = "0.1.0",
            edition = "2024",
            authors = [],
            description = "",
            homepage = "",
            include = [],
            keywords = [],
            license = "AGPL 3.0",
            publish = false,
            repository = "",
            rust_version = "1.85.0",
        }
    };
}

macro_rules! define_workspace_members_part1 {
    () => {
        "submodules/hyper",
        "crates/addr2line-bin",
        "crates/monster_math_traits",
        "crates/factory_abi",
        "crates/ast_parser_impl",
        "tools/cargo-repo-sync",
        "tools/dep2submodule",
        "tools/generate_workspace_deps",
        "tools/cargo-workspace-from-tree",
        "tools/secret-manager-rs",
        "tools/cargo-submodule-tool-lib",
        "tools/syn-adapter-lib",
        "tools/feature-permutation-builder",
        "tools/cargo-feature-adapter",
        "tools/cargo-llm-bootstrap",
        "tools/rust-src-scanner",
        "tools/graph-petal-generator",
        "tools/monster-grouper",
        "tools/trait-fixer",
        "submodules/rust/compiler/lib-kleene-op",
        "submodules/rust/compiler/lib-macro-rule",
        "submodules/rust/compiler/lib-matcher-loc",
        "submodules/rust/compiler/macro_wrapper_lib",
        "submodules/rust/compiler/lib-metavar-expr",
        "submodules/rust/compiler/lib-token-tree",
        "submodules/rust/compiler/rustc_ast",
        "submodules/rust/compiler/rustc_data_structures",
        "submodules/rust/compiler/rustc_driver",
        "submodules/rust/compiler/rustc_hir",
        "submodules/rust/compiler/rustc_index",
        "submodules/rust/compiler/rustc_interface",
        "submodules/rust/compiler/rustc_lint",
        "submodules/rust/compiler/rustc_middle",
        "submodules/rust/compiler/rustc_session",
        "submodules/rust/compiler/rustc_span",
        "submodules/rust/src/tools/clippy/rustc_tools_util",
        "submodules/rust/compiler/rustc_fluent_macro",
        "submodules/static-assertions-rs/proc",
        "submodules/rowan",
        "submodules/expect-test",
        "submodules/dot-parser",
        "submodules/dot-parser/macros",
        "submodules/rocksdb",
        "submodules/rocksdb/librocksdb-sys",
        "crates/trait-fixer-attribute-reader-trait",
        "crates/trait-fixer-attribute-reader-real",
        "crates/trait-fixer-attribute-reader-mock",
        "crates/trait-fixer-compiler-host-trait",
        "crates/trait-fixer-compiler-host-real",
        "crates/trait-fixer-compiler-host-mock",
        "crates/trait-fixer-core-trait",
        "crates/trait-fixer-core-real",
        "crates/trait-fixer-core-mock",
        "crates/trait-fixer-hir-info-trait",
        "crates/trait-fixer-hir-info-real",
        "crates/trait-fixer-hir-info-mock"
    };
}

macro_rules! define_workspace_members_part2 {
    () => {
        "crates/trait-fixer-lang-items-trait",
        "crates/trait-fixer-lang-items-real",
        "crates/trait-fixer-lang-items-mock",
        "crates/trait-fixer-query-context-trait",
        "crates/trait-fixer-query-context-real",
        "crates/trait-fixer-query-context-mock",
        "crates/trait-fixer-rules-trait",
        "crates/trait-fixer-rules-real",
        "crates/trait-fixer-rules-mock",
        "crates/trait-fixer-rustc-mock",
        "crates/trait-fixer-trait-checker-trait",
        "crates/trait-fixer-trait-checker-real",
        "crates/trait-fixer-trait-checker-mock",
        "tests/trait_fixer_mocks",
        "tests/real_rules_test",
        "submodules/rust/crates/cvs-macro-lib",
        "submodules/rust/crates/cvs-macro-test-crate",
        "crates/rust-nix-bootstrap",
        "submodules/rust/compiler/expand_utils_test",
        "submodules/rust/compiler/rustc_expand",
        "submodules/rust/compiler/rustc_expand_base_lib",
        "submodules/rust/compiler/rustc_serialize",
        "submodules/rust/compiler/introspector/core",
        "repl_server",
        "submodules/rust/compiler/rustc_expand_patches",
        "tools/type-reporter",
        "submodules/rust/compiler/rustc_expand_base_lib_errors",
        "submodules/rust/compiler/rustc_expand_base_lib_macros",
        "submodules/rust/compiler/rustc_expand_base_lib_test_driver",
        "ticket_data_generator",
        "submodules/split-decls-rs",
        "submodules/split-decls-rs/workspace-merge",
        "submodules/split-decls-rs/split-decls-types",
        "cargo-toml-generator-types",
        "cargo-toml-generator-macros"
    };
}

macro_rules! define_workspace_dependencies_part1 {
    () => {
        dep_path!("split-decls-types", "submodules/split-decls-rs/split-decls-types"),
        dep_path!("split_decls_types", "submodules/split-decls-rs/split-decls-types"),
        dep_version!("databake", "*"),
        dep_version!("harfbuzz-traits", "*"),
        dep_version!("icu_collections", "*"),
        dep_version!("icu_provider", "*"),
        dep_version!("utf16_iter", "*"),
        dep_version!("utf8_iter", "*"),
        dep_version!("write16", "*"),
        dep_version!("zerovec", "*"),
        dep_version!("arraystring", "*"),
        dep_path!("atoi", "*"),
        dep_path!("icu_normalizer_data", "*"),
        dep_path!("detone", "*"),
        dep_version!("icu_locale_core", "*"),
        dep_version!("displaydoc", "*"),
        dep_path!("synstructure", "submodules/synstructure"),
        dep_version!("unicode-bidi", "*"),
        dep_version!("zerotrie", "*"),
        dep_version!("dot", "*"),
        dep_version!("yoke", "*"),
        dep_version!("postcard", "*"),
        dep_version!("rkyv", "*"),
        dep_version!("writeable", "*"),
        dep_version!("pulldown-cmark-to-cmark", "*"),
        dep_path!("aho_corasick", "submodules/aho-corasick"),
        dep_version!("shell-escape", "0.1.5"),
        dep_version!("winnow", "0.7.13"),
        dep_version!("schemars", "1.0.5"),
        dep_version!("unic-langid", "0.9"),
        dep_version!("notify", "6.1.1"),
        dep_version!("proptest", "1.9.0"),
        dep_version!("miow", "0.6.1"),
        dep_version!("percent-encoding", "2.3.2"),
        dep_version!("iai", "0.1"),
        dep_version!("intl_pluralrules", "7.0"),
        dep_version!("similar", "2.7.0"),
        dep_version!("perf-event-open-sys", "3.0.0"),
        dep_version!("security-framework", "3.5.1"),
        dep_version!("filetime", "0.2.26"),
        dep_version!("jobserver", "0.1.34"),
        dep_version!("async-trait", "0.1.79"),
        dep_version!("serde-untagged", "0.1.9"),
        dep_version!("fluent-langneg", "0.13"),
        dep_version!("log", "0.4"),
        dep_version!("rustyline", "14.0.0"),
        dep_version!("openssl", "0.10.74"),
        dep_version!("memfd", "0.6.5"),
        dep_version!("ignore", "0.4.25"),
        dep_path!("strsim", "submodules/strsim-rs"),
        dep_path!("ide-db", "submodules/rust-analyzer/crates/ide-db"),
        dep_path!("getrandom", "submodules/getrandom"),
        dep_path!("opener", "submodules/opener/opener"),
        dep_path!("async-std", "submodules/async-std"),
        dep_table!("ra-ap-rustc_type_ir", package = "rustc_type_ir", path = "./submodules/rust/compiler/rustc_type_ir"),
        dep_path!("ppv-lite86", "submodules/cryptocorrosion/utils-simd/ppv-lite86"),
        dep_path!("sharded-slab", "submodules/sharded-slab"),
        dep_path!("trybuild", "submodules/trybuild"),
        dep_path!("iana-time-zone", "submodules/iana-time-zone"),
        dep_path!("libgit2-sys", "submodules/git2-rs/libgit2-sys"),
        dep_path!("syn", "submodules/syn"),
        dep_path!("group", "submodules/group"),
        dep_path!("arrayvec", "submodules/arrayvec")
    };
}

macro_rules! define_workspace_dependencies_part2 {
    () => {
        dep_path!("gix-revwalk", "submodules/gitoxide/gix-revwalk"),
        dep_path!("cfg-if", "submodules/cfg-if"),
        dep_path!("md5", "submodules/md5"),
        dep_path!("fuzz", "submodules/quinn/fuzz"),
        dep_path!("constant_time_eq", "submodules/constant_time_eq"),
        dep_path!("gix-validate", "submodules/gitoxide/gix-validate"),
        dep_path!("introspector_decl2_macros", "submodules/patch-build-rs/introspector_decl2_macros"),
        dep_path!("is_executable", "submodules/is_executable"),
        dep_path!("gix-ignore", "submodules/gitoxide/gix-ignore"),
        dep_path!("toml_parser", "submodules/toml/crates/toml_parser"),
        dep_path!("windows_i686_gnullvm", "submodules/windows-rs/crates/targets/i686_gnullvm"),
        dep_path!("cpufeatures", "submodules/utils/cpufeatures"),
        dep_path!("lock_api", "submodules/parking_lot/lock_api"),
        dep_table!("serde", version = "1.0", features = ["derive"]),
        dep_path!("rustfix", "submodules/cargo/crates/rustfix"),
        dep_path!("serde-value", "submodules/serde-value"),
        dep_path!("gix-fetchhead", "submodules/gitoxide/gix-fetchhead"),
        dep_path!("expand_utils_lib", "submodules/rust/compiler/expand_utils_lib"),
        dep_path!("gix-pathspec", "submodules/gitoxide/gix-pathspec"),
        dep_path!("serde_core", "submodules/serde/serde_core"),
        dep_path!("paths", "submodules/rust-analyzer/crates/paths"),
        dep_path!("yoke-derive", "submodules/icu4x/utils/yoke/derive"),
        dep_path!("async-graphql-derive", "submodules/async-graphql/derive"),
        dep_path!("imara-diff", "submodules/imara-diff"),
        dep_path!("sval", "submodules/sval"),
        dep_path!("gix-features", "submodules/gitoxide/gix-features"),
        dep_path!("sized-chunks", "submodules/sized-chunks"),
        dep_path!("crossbeam", "submodules/crossbeam/"),
        dep_path!("crosstermion", "submodules/crosstermion/"),
        dep_path!("is-terminal", "submodules/is-terminal/"),
        dep_path!("glob", "submodules/glob"),
        dep_path!("document-features", "submodules/document-features"),
        dep_path!("hmac", "submodules/MACs/hmac"),
        dep_path!("memoffset", "submodules/memoffset"),
        dep_path!("hash32", "submodules/hash32"),
        dep_path!("simd-adler32", "submodules/simd-adler32"),
        dep_path!("unicode-segmentation", "submodules/unicode-segmentation"),
        dep_path!("futures-lite", "submodules/futures-lite"),
        dep_path!("p384", "submodules/elliptic-curves/p384"),
        dep_path!("potential_utf", "submodules/icu4x/utils/potential_utf"),
        dep_path!("gix-packetline", "submodules/gitoxide/gix-packetline"),
        dep_path!("linux-raw-sys", "submodules/linux-raw-sys"),
        dep_path!("anstyle-parse", "submodules/anstyle/crates/anstyle-parse"),
        dep_path!("assert-impl", "submodules/assert-impl"),
        dep_path!("const-oid", "submodules/formats/const-oid"),
        dep_path!("env_logger", "submodules/env_logger"),
        dep_path!("nix", "submodules/nix"),
        dep_path!("lib-metavar-expr", "submodules/rust/compiler/lib-metavar-expr"),
        dep_path!("tracing-tower", "submodules/tracing/tracing-tower"),
        dep_path!("fallible-iterator", "submodules/rust-fallible-iterator"),
        dep_path!("gix-status", "submodules/gitoxide/gix-status"),
        dep_path!("gix-dir", "submodules/gitoxide/gix-dir"),
        dep_path!("gix-merge", "submodules/gitoxide/gix-merge"),
        dep_path!("crates-io", "submodules/cargo/crates/crates-io"),
        dep_path!("addr2line", "submodules/addr2line"),
        dep_path!("faster-hex", "submodules/faster-hex"),
        dep_path!("bytes", "submodules/bytes"),
        dep_path!("ruzstd", "submodules/zstd-rs/ruzstd"),
        dep_path!("clap_builder", "submodules/clap/clap_builder"),
        dep_path!("unicode-ident", "submodules/unicode-ident"),
        dep_path!("fixedbitset", "submodules/fixedbitset")
    };
}

macro_rules! define_workspace_dependencies_part3 {
    () => {
        dep_path!("scoped-tls", "submodules/scoped-tls"),
        dep_path!("lazy_static", "submodules/lazy-static"),
        dep_table!("ra-ap-rustc_pattern_analysis", package = "rustc_pattern_analysis", path = "./submodules/rust/compiler/rustc_pattern_analysis"),
        dep_path!("anstyle", "submodules/anstyle/crates/anstyle"),
        dep_path!("rand", "submodules/rand"),
        dep_path!("rustc_session", "submodules/rust/compiler/rustc_session"),
        dep_path!("lzma-rust2", "submodules/lzma-rust2"),
        dep_path!("env_filter", "submodules/env_logger/crates/env_filter"),
        dep_path!("gix-prompt", "submodules/gitoxide/gix-prompt"),
        dep_path!("memchr", "submodules/memchr"),
        dep_table!("query-group", package = "query-group-macro", path = "./submodules/rust-analyzer/crates/query-group-macro"),
        dep_path!("introspector_decl_common", "submodules/patch-build-rs/introspector_decl_common"),
        dep_path!("prodash", "submodules/prodash"),
        dep_path!("test-utils", "submodules/rust-analyzer/crates/test-utils"),
        dep_path!("gix-filter", "submodules/gitoxide/gix-filter"),
        dep_path!("gix-utils", "submodules/gitoxide/gix-utils"),
        dep_path!("syntax", "./submodules/rust-analyzer/crates/syntax"),
        dep_path!("crossbeam-deque", "submodules/crossbeam/crossbeam-deque"),
        dep_path!("rustc_ast", "submodules/rust/compiler/rustc_ast"),
        dep_path!("typesize-derive", "submodules/typesize/typesize-derive"),
        dep_path!("hir-def", "submodules/rust-analyzer/crates/hir-def"),
        dep_path!("libloading", "submodules/rust_libloading"),
        dep_path!("rustc_feature", "submodules/rust/compiler/rustc_feature"),
        dep_path!("is_terminal_polyfill", "submodules/is_terminal_polyfill"),
        dep_path!("unicode-bom", "submodules/unicode-bom"),
        dep_path!("itoa", "submodules/itoa"),
        dep_path!("dot-parser-macros", "submodules/dot-parser/macros"),
        dep_path!("supports-unicode", "submodules/supports-unicode"),
        dep_path!("colorchoice", "submodules/anstyle/crates/colorchoice"),
        dep_table!("gix-tempfile", features = [], path = "submodules/gitoxide/gix-tempfile"),
        dep_path!("cargo-credential", "submodules/cargo/credential/cargo-credential"),
        dep_path!("rustc_serialize", "submodules/rust/compiler/rustc_serialize"),
        dep_path!("xattr", "submodules/xattr"),
        dep_table!("pasetors", features = ["v3", "serde"], path = "submodules/pasetors"),
        dep_path!("syntax-bridge", "./submodules/rust-analyzer/crates/syntax-bridge"),
        dep_path!("gix-actor", "submodules/gitoxide/gix-actor"),
        dep_path!("minimal-lexical", "submodules/minimal-lexical"),
        dep_path!("tera", "submodules/tera"),
        dep_path!("thread_local", "submodules/thread_local-rs"),
        dep_path!("ide-completion", "submodules/rust-analyzer/crates/ide-completion"),
        dep_path!("http-auth", "submodules/http-auth"),
        dep_path!("aho-corasick", "submodules/aho-corasick"),
        dep_path!("primeorder", "submodules/elliptic-curves/primeorder"),
        dep_path!("regex-syntax", "submodules/regex/regex-syntax"),
        dep_table!("clap", features = ["derive"], path = "submodules/clap"),
        dep_path!("gix-lfs", "submodules/gitoxide/gix-lfs"),
        dep_path!("load-cargo", "submodules/rust-analyzer/crates/load-cargo"),
        dep_table!("ra-ap-rustc_next_trait_solver", package = "rustc_next_trait_solver", path = "./submodules/rust/compiler/rustc_next_trait_solver"),
        dep_path!("mio", "submodules/mio"),
        dep_path!("tokio-test", "submodules/tokio/tokio-test"),
        dep_path!("tracing-tree", "submodules/tracing-tree"),
        dep_path!("windows-implement", "submodules/windows-rs/crates/libs/implement"),
        dep_path!("windows-numerics", "submodules/windows-rs/crates/libs/numerics"),
        dep_path!("rustc_apfloat", "submodules/rustc_apfloat"),
        dep_path!("pest_derive", "submodules/pest/derive"),
        dep_path!("powerfmt-macros", "submodules/powerfmt/powerfmt-macros"),
        dep_table!("dashmap", features = ["raw-api", "inline"], path = "submodules/dashmap", version = "7.0.0-hack"),
        dep_path!("futures-util", "submodules/futures-rs/futures-util"),
        dep_table!("triomphe", features = ["std"], version = "0.1.14"),
        dep_path!("anyhow", "submodules/anyhow"),
        dep_path!("futures-macro", "submodules/futures-rs/futures-macro"),
        dep_path!("windows_x86_64_gnullvm", "submodules/windows-rs/crates/targets/x86_64_gnullvm")
    };
}

macro_rules! define_workspace_dependencies_part4 {
    () => {
        dep_path!("rustc_middle", "submodules/rust/compiler/rustc_middle"),
        dep_table!("flate2", features = ["zlib-rs"], version = "1.1.5"),
        dep_path!("crossbeam-utils", "submodules/crossbeam/crossbeam-utils"),
        dep_path!("indexmap", "submodules/indexmap"),
        dep_path!("camino", "submodules/camino"),
        dep_path!("static_assertions", "submodules/static-assertions-rs"),
        dep_path!("gix-odb", "submodules/gitoxide/gix-odb"),
        dep_path!("clap_complete", "submodules/clap/clap_complete"),
        dep_path!("colorify", "submodules/colorify"),
        dep_path!("crypto-bigint", "submodules/crypto-bigint"),
        dep_path!("autocfg", "submodules/autocfg"),
        dep_path!("proc-macro-srv", "submodules/rust-analyzer/crates/proc-macro-srv"),
        dep_path!("tool-traits-lib", "./tools/tool-traits-lib"),
        dep_path!("heapless", "submodules/heapless"),
        dep_table!("parking_lot_core", path = "submodules/parking_lot/core", version = "0.9.13"),
        dep_path!("quickcheck", "submodules/quickcheck"),
        dep_path!("windows_x86_64_msvc", "submodules/windows-rs/crates/targets/x86_64_msvc"),
        dep_path!("rustc_parse", "submodules/rust/compiler/rustc_parse"),
        dep_path!("windows_x86_64_gnu", "submodules/windows-rs/crates/targets/x86_64_gnu"),
        dep_table!("thin-vec", path = "submodules/thin-vec", version = "0.2.14"),
        dep_path!("salsa-macros", "submodules/salsa/components/salsa-macros"),
        dep_path!("tt", "./submodules/rust-analyzer/crates/tt"),
        dep_path!("windows-bindings", "submodules/jni-rs/windows-bindings"),
        dep_path!("block-buffer", "submodules/utils/block-buffer"),
        dep_path!("base-db", "submodules/rust-analyzer/crates/base-db"),
        dep_path!("parser", "submodules/rust-analyzer/crates/parser"),
        dep_path!("windows-bindgen", "submodules/windows-rs/crates/libs/bindgen"),
        dep_path!("toml_datetime", "submodules/toml/crates/toml_datetime"),
        dep_path!("atomic-maybe-uninit", "submodules/atomic-maybe-uninit"),
        dep_path!("split-decls-rs", "submodules/split-decls-rs"),
        dep_path!("md-5", "submodules/hashes/md5"),
        dep_path!("rand_xorshift", "submodules/rngs/rand_xorshift"),
        dep_table!("tokio", features = ["full"], path = "submodules/tokio/tokio"),
        dep_path!("span", "./submodules/rust-analyzer/crates/span"),
        dep_path!("digest", "submodules/traits/digest"),
        dep_path!("rustc_driver_impl", "submodules/rust/compiler/rustc_driver_impl"),
        dep_path!("fnv", "submodules/rust-fnv"),
        dep_path!("curl-sys", "submodules/curl-rust/curl-sys"),
        dep_path!("gix-index", "submodules/gitoxide/gix-index"),
        dep_path!("clru", "submodules/clru-rs"),
        dep_path!("rustc_span", "submodules/rust/compiler/rustc_span"),
        dep_path!("cpp_demangle", "submodules/cpp_demangle"),
        dep_path!("serial_test", "submodules/serial_test/serial_test"),
        dep_path!("gix-tui", "submodules/gitoxide/gix-tui"),
        dep_path!("line-index", "submodules/rust-analyzer/lib/line-index"),
        dep_path!("os_info", "submodules/os_info/os_info"),
        dep_path!("windows-services", "submodules/windows-rs/crates/libs/services"),
        dep_path!("cargo-repo-sync-lib", "tools/cargo-repo-sync-lib"),
        dep_path!("git2-curl", "submodules/git2-rs/git2-curl"),
        dep_path!("gix-path", "submodules/gitoxide/gix-path"),
        dep_path!("itertools", "submodules/itertools"),
        dep_path!("arc-swap", "submodules/arc-swap"),
        dep_path!("bstr", "submodules/bstr"),
        dep_path!("rustc_ast_pretty", "./submodules/rust-analyzer/crates/rustc_ast_pretty"),
        dep_path!("async-stream", "submodules/async-stream-vendored"),
        dep_path!("gix-attributes", "submodules/gitoxide/gix-attributes"),
        dep_path!("gix-quote", "submodules/gitoxide/gix-quote"),
        dep_path!("icu_properties_data", "submodules/icu4x/provider/data/properties"),
        dep_path!("async-graphql", "submodules/async-graphql")
    };
}

macro_rules! define_workspace_dependencies_part5 {
    () => {
        include!("generated/part5.rs")
    };
}


macro_rules! mkbuildrs {
    () => {
        define_package_config!()
    };
}